# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: neuralvl/data/dim.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='neuralvl/data/dim.proto',
  package='neural',
  syntax='proto3',
  serialized_options=_b('\n\023com.xuebingli.protoB\010DimProtoP\001'),
  serialized_pb=_b('\n\x17neuralvl/data/dim.proto\x12\x06neural\"z\n\rReduceRequest\x12 \n\x07\x64\x61taset\x18\x01 \x01(\x0e\x32\x0f.neural.Dataset\x12$\n\talgorithm\x18\x02 \x01(\x0e\x32\x11.neural.Algorithm\x12\x0e\n\x06number\x18\x03 \x01(\x05\x12\x11\n\tdimention\x18\x04 \x01(\x05\"y\n\x0bReduceReply\x12&\n\x07request\x18\x01 \x01(\x0b\x32\x15.neural.ReduceRequest\x12 \n\x07points2\x18\x02 \x03(\x0b\x32\x0f.neural.Point2D\x12 \n\x07points3\x18\x03 \x03(\x0b\x32\x0f.neural.Point3D\"\x1f\n\x07Point2D\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"*\n\x07Point3D\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02*\x1e\n\tAlgorithm\x12\x07\n\x03PCA\x10\x00\x12\x08\n\x04TSNE\x10\x01*\x14\n\x07\x44\x61taset\x12\t\n\x05MNIST\x10\x00\x32I\n\x06Reduce\x12?\n\x0fReduceDimention\x12\x15.neural.ReduceRequest\x1a\x13.neural.ReduceReply\"\x00\x42!\n\x13\x63om.xuebingli.protoB\x08\x44imProtoP\x01\x62\x06proto3')
)

_ALGORITHM = _descriptor.EnumDescriptor(
  name='Algorithm',
  full_name='neural.Algorithm',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PCA', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TSNE', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=359,
  serialized_end=389,
)
_sym_db.RegisterEnumDescriptor(_ALGORITHM)

Algorithm = enum_type_wrapper.EnumTypeWrapper(_ALGORITHM)
_DATASET = _descriptor.EnumDescriptor(
  name='Dataset',
  full_name='neural.Dataset',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MNIST', index=0, number=0,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=391,
  serialized_end=411,
)
_sym_db.RegisterEnumDescriptor(_DATASET)

Dataset = enum_type_wrapper.EnumTypeWrapper(_DATASET)
PCA = 0
TSNE = 1
MNIST = 0



_REDUCEREQUEST = _descriptor.Descriptor(
  name='ReduceRequest',
  full_name='neural.ReduceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dataset', full_name='neural.ReduceRequest.dataset', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='algorithm', full_name='neural.ReduceRequest.algorithm', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='number', full_name='neural.ReduceRequest.number', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dimention', full_name='neural.ReduceRequest.dimention', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=157,
)


_REDUCEREPLY = _descriptor.Descriptor(
  name='ReduceReply',
  full_name='neural.ReduceReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request', full_name='neural.ReduceReply.request', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='points2', full_name='neural.ReduceReply.points2', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='points3', full_name='neural.ReduceReply.points3', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=280,
)


_POINT2D = _descriptor.Descriptor(
  name='Point2D',
  full_name='neural.Point2D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='neural.Point2D.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='neural.Point2D.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=282,
  serialized_end=313,
)


_POINT3D = _descriptor.Descriptor(
  name='Point3D',
  full_name='neural.Point3D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='neural.Point3D.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='neural.Point3D.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='neural.Point3D.z', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=315,
  serialized_end=357,
)

_REDUCEREQUEST.fields_by_name['dataset'].enum_type = _DATASET
_REDUCEREQUEST.fields_by_name['algorithm'].enum_type = _ALGORITHM
_REDUCEREPLY.fields_by_name['request'].message_type = _REDUCEREQUEST
_REDUCEREPLY.fields_by_name['points2'].message_type = _POINT2D
_REDUCEREPLY.fields_by_name['points3'].message_type = _POINT3D
DESCRIPTOR.message_types_by_name['ReduceRequest'] = _REDUCEREQUEST
DESCRIPTOR.message_types_by_name['ReduceReply'] = _REDUCEREPLY
DESCRIPTOR.message_types_by_name['Point2D'] = _POINT2D
DESCRIPTOR.message_types_by_name['Point3D'] = _POINT3D
DESCRIPTOR.enum_types_by_name['Algorithm'] = _ALGORITHM
DESCRIPTOR.enum_types_by_name['Dataset'] = _DATASET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReduceRequest = _reflection.GeneratedProtocolMessageType('ReduceRequest', (_message.Message,), dict(
  DESCRIPTOR = _REDUCEREQUEST,
  __module__ = 'neuralvl.data.dim_pb2'
  # @@protoc_insertion_point(class_scope:neural.ReduceRequest)
  ))
_sym_db.RegisterMessage(ReduceRequest)

ReduceReply = _reflection.GeneratedProtocolMessageType('ReduceReply', (_message.Message,), dict(
  DESCRIPTOR = _REDUCEREPLY,
  __module__ = 'neuralvl.data.dim_pb2'
  # @@protoc_insertion_point(class_scope:neural.ReduceReply)
  ))
_sym_db.RegisterMessage(ReduceReply)

Point2D = _reflection.GeneratedProtocolMessageType('Point2D', (_message.Message,), dict(
  DESCRIPTOR = _POINT2D,
  __module__ = 'neuralvl.data.dim_pb2'
  # @@protoc_insertion_point(class_scope:neural.Point2D)
  ))
_sym_db.RegisterMessage(Point2D)

Point3D = _reflection.GeneratedProtocolMessageType('Point3D', (_message.Message,), dict(
  DESCRIPTOR = _POINT3D,
  __module__ = 'neuralvl.data.dim_pb2'
  # @@protoc_insertion_point(class_scope:neural.Point3D)
  ))
_sym_db.RegisterMessage(Point3D)


DESCRIPTOR._options = None

_REDUCE = _descriptor.ServiceDescriptor(
  name='Reduce',
  full_name='neural.Reduce',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=413,
  serialized_end=486,
  methods=[
  _descriptor.MethodDescriptor(
    name='ReduceDimention',
    full_name='neural.Reduce.ReduceDimention',
    index=0,
    containing_service=None,
    input_type=_REDUCEREQUEST,
    output_type=_REDUCEREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_REDUCE)

DESCRIPTOR.services_by_name['Reduce'] = _REDUCE

# @@protoc_insertion_point(module_scope)
