# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from neuralvl.data import dim_pb2 as neuralvl_dot_data_dot_dim__pb2


class ReduceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ReduceDimention = channel.unary_unary(
        '/neural.Reduce/ReduceDimention',
        request_serializer=neuralvl_dot_data_dot_dim__pb2.ReduceRequest.SerializeToString,
        response_deserializer=neuralvl_dot_data_dot_dim__pb2.ReduceReply.FromString,
        )


class ReduceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ReduceDimention(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ReduceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ReduceDimention': grpc.unary_unary_rpc_method_handler(
          servicer.ReduceDimention,
          request_deserializer=neuralvl_dot_data_dot_dim__pb2.ReduceRequest.FromString,
          response_serializer=neuralvl_dot_data_dot_dim__pb2.ReduceReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'neural.Reduce', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
